# Generated by Django 3.1.4 on 2021-02-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_register_tb_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register_tb',
            new_name='register_tb1',
        ),
    ]
