# Generated by Django 3.1.4 on 2021-02-04 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_catagory_tb'),
        ('seller', '0004_product_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='seller',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='seller.register_tb1'),
        ),
        migrations.AlterField(
            model_name='product_tb',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.catagory_tb'),
        ),
    ]
