# Generated by Django 3.1.4 on 2021-02-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20210204_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='file',
            field=models.FileField(default='no pic', upload_to=''),
        ),
    ]
