# Generated by Django 3.1.4 on 2021-02-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_product_tb_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='price',
            field=models.IntegerField(),
        ),
    ]
