# Generated by Django 3.1.4 on 2021-02-09 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_product_tb_file'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_to_cart_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.register_tb1')),
            ],
        ),
    ]
