# Generated by Django 3.1.4 on 2021-02-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_add_to_cart_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_to_cart_tb',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buyer.register_tb'),
        ),
    ]
