# Generated by Django 3.1.4 on 2021-02-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_order_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tb',
            name='status',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
